parameters:
  bzl.zf_view.assetic.formula_loader.class: Bzl\Bundle\ZfViewBundle\Assetic\ZfViewFormulaLoader

services:
  bzl.zf_view.assetic.formula_loader:
    class: %bzl.zf_view.assetic.formula_loader.class%
    tags:
      - { name: assetic.formula_loader, alias: zf_view }