parameters:
  bez.zf_view.assetic.formula_loader.class: Bez\ZfViewBundle\Assetic\ZfViewFormulaLoader

services:
  bez.zf_view.assetic.formula_loader:
    class: %bez.zf_view.assetic.formula_loader.class%
    arguments: ["@assetic.asset_factory"]
    tags:
      - { name: assetic.formula_loader, alias: zf_view }
      - { name: assetic.formula_loader, alias: phtml }