parameters:
  bez.zf_view.engine.class: Bez\ZfViewBundle\Templating\ZfViewEngine
  bez.zf_view.class: Zend\View\View
  bez.zf_view.resolver.aggregate.class: Zend\View\Resolver\AggregateResolver
  zend.event_manager.class: Zend\EventManager\EventManager

  bez.zf_view.resolver.logical_names.class: Bez\ZfViewBundle\Zend\View\Resolver\LogicalNameResolver

services:

  bez.zf_view.engine:
    class: %bez.zf_view.engine.class%
    arguments:
      ["@bez.zf_view", "@bez.zf_view.resolver.aggregate", "@service_container"]
    tags:
      - { name: templating.engine }

  templating.engine.zf_view:
    alias: bez.zf_view.engine

  templating.engine.phtml:
    alias: bez.zf_view.engine

  bez.zf_view:
    class: %bez.zf_view.class%
    calls:
      - [setEventManager, ["@zend.event_manager"]]

  bez.zf_view.resolver.aggregate:
    class: %bez.zf_view.resolver.aggregate.class%
    calls:
      - [attach, ["@bez.zf_view.resolver.logical_names"]]

  bez.zf_view.resolver.logical_names:
    class: %bez.zf_view.resolver.logical_names.class%
    arguments: ["@templating.loader", "@templating.name_parser", "@templating.locator"]

  bez.zf_view.helper_manager:
    class: Bez\ZfViewBundle\Zend\View\AggregatePluginManager

  bez.zf_view.helper_manager.original:
    class: Bez\ZfViewBundle\Zend\View\HelperPluginManager
    tags:
      - { name: zf_view.plugin_manager, priority: 1 }

  bez.zf_view.helper_manager.in_container:
    class: Bez\ZfViewBundle\Zend\View\HelpersInContainer
    arguments: ["@service_container"]
    tags:
      - { name: zf_view.plugin_manager, priority: 2 }

  bez.zf_view.renderer.php:
    class: Zend\View\Renderer\PhpRenderer
    calls:
      - [setResolver, ["@bez.zf_view.resolver.aggregate"]]
      - [setHelperPluginManager, ["@bez.zf_view.helper_manager"]]

  zend.event_manager:
    class: %zend.event_manager.class%


  bez.zf_view.strategy.php:
    class: Zend\View\Strategy\PhpRendererStrategy
    arguments: ["@bez.zf_view.renderer.php"]
    tags:
      - { name: zend.event_listener }

  bez.zf_view.kernel.event_listener:
    class: Bez\ZfViewBundle\EventListener\KernelListener
    arguments: ["@zend.event_manager", "@annotation_reader", "@bez.zf_view.engine", "@sensio_framework_extra.view.guesser"]
    tags:
      - {name: kernel.event_subscriber }
