parameters:

services:
  bzl.view_helper.path:
    class: Bzl\Bundle\ZfViewBundle\Zend\View\Helper\Path
    arguments: ["@router"]
    tags:
      - { name: view_helper, alias: path }

  bzl.view_helper.url:
    class: Bzl\Bundle\ZfViewBundle\Zend\View\Helper\Url
    arguments: ["@router"]
    tags:
      - { name: view_helper, alias: url }

  bzl.view_helper.security:
    class: Bzl\Bundle\ZfViewBundle\Zend\View\Helper\Security
    arguments: ["@security.context"]
    tags:
      - { name: view_helper, alias: security }

  bzl.view_helper.translation:
    class: Bzl\Bundle\ZfViewBundle\Zend\View\Helper\Translation
    arguments: ["@translator"]
    tags:
      - { name: view_helper, alias: trans }

  bzl.view_helper.controller_renderer:
    class: Bzl\Bundle\ZfViewBundle\Zend\View\Helper\ControllerRenderer
    arguments: ["@fragment.handler"]
    tags:
      - { name: view_helper, alias: controller }

  bzl.view_helper.asset:
    class: Bzl\Bundle\ZfViewBundle\Zend\View\Helper\Asset
    arguments: ["@service_container"]
    tags:
      - { name: view_helper, alias: asset }